workflows:
  ionic-capacitor-ios-workflow-no-capgo:
    name: Capacitor iOS Workflow (No Capgo)
    max_build_duration: 120
    environment:
      node: latest
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Build
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install
          bun run build
      - name: Update dependencies and copy web assets to native project
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync
      - name: Build iOS app
        script: |
          cd ios/App
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15' -derivedDataPath build
      - name: Create iOS bundle
        script: |
          cd ios/App/build/Build/Products/Debug-iphonesimulator
          zip -r ../../../../../../ios-app.zip App.app
    artifacts:
      - ios-app.zip
