workflows:
  ionic-capacitor-ios-workflow-npm:
    name: Capacitor iOS Workflow (npm)
    max_build_duration: 120
    environment:
      groups:
        - capgo
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build
        script: |
          npm run build
      - name: Install npm dependencies for Ionic project
        script: |
          npx @capgo/cli login $CAPGO_TOKEN
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Upload to Capgo
        script: |
          npx @capgo/cli upload
