workflows:
  ionic-capacitor-ios-workflow:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - capgo
    scripts:
      - name: Build
        script: |
          bun install
          bun run build
      - name: Install npm dependencies for Ionic project
        script: |
          npx @capgo/cli login $CAPGO_TOKEN
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Upload to Capgo
        script: |
          npx @capgo/cli upload
