workflows:
  ionic-capacitor-ios-workflow:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - capgo
      node: latest
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Build
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install
          bun run build
      - name: Install npm dependencies for Ionic project
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx @capgo/cli login $CAPGO_TOKEN
      - name: Update dependencies and copy web assets to native project
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync
      - name: Upload to Capgo
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx @capgo/cli upload
