workflows:
  ionic-capacitor-ios-workflow-robust-no-capgo:
    name: Capacitor iOS Workflow (Robust - No Capgo)
    max_build_duration: 120
    environment:
      node: latest
    scripts:
      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Build
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install
          bun run build
      - name: Update dependencies and copy web assets to native project
        script: |
          export PATH="$HOME/.bun/bin:$PATH"
          npx cap sync
      - name: List available simulators
        script: |
          xcrun simctl list devices available
      - name: Build iOS app
        script: |
          cd ios/App
          pod install
          # Try multiple simulator options for maximum compatibility
          if xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,id=FD1BF54E-4D3D-45B8-AF09-425C68025542' -derivedDataPath build; then
            echo "Build successful with iPhone 15"
          elif xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,id=0AC9444F-3A74-40DC-A41C-A6B973A31ABB' -derivedDataPath build; then
            echo "Build successful with iPhone 16"
          elif xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,id=BF6788C2-AC16-4044-A32F-351AFB5B9E25' -derivedDataPath build; then
            echo "Build successful with iPhone 14"
          elif xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15' -derivedDataPath build; then
            echo "Build successful with iPhone 15 by name"
          elif xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 16' -derivedDataPath build; then
            echo "Build successful with iPhone 16 by name"
          else
            echo "All simulator builds failed"
            exit 1
          fi
      - name: Create iOS bundle
        script: |
          cd ios/App/build/Build/Products/Debug-iphonesimulator
          zip -r ../../../../../../ios-app.zip App.app
    artifacts:
      - ios-app.zip
